#!/usr/bin/env python

"""
Get and compile dependencies for HactEngine.

This script will download and compile most of the dependencies needed for
HactEngine's development. It even downloads the Qt installer for you.

Some of the dependencies are "header only" or otherwise do not require
installing, but they are downloaded as well.

There are some tools which HactEngine does not directly depend on, but are
required to compile the engine's dependencies. If these are small and simple
to compile (like GNU Readline), they are downloaded and compiled as well.
"""

# pylint: disable = C0302, R0913

import argparse
import multiprocessing
import os
import posixpath
import platform
import subprocess
import sys


print("System info")
print("===========")
print("OS name:            " + os.name)
print("Platform:           " + platform.system())
print("Linux distribution: " + platform.linux_distribution()[0])
print("CPU cores:          " + str(multiprocessing.cpu_count()))
print("")

PLATFORM_LINUX      = False
PLATFORM_OSX        = False
PLATFORM_WINDOWS    = False
PLATFORM_WINDOWS_32 = False
PLATFORM_WINDOWS_64 = False


if platform.system() == "Linux":
    print("Linux detected")
    PLATFORM_LINUX = True
    
    if platform.linux_distribution()[0] == "Ubuntu":
        print("Install these dependencies:")
        print(
            "    sudo apt-get install automake build-essential cmake curl git libtool"
        )
    elif platform.linux_distribution()[0] == "Fedora":
        print("Install these dependencies:")
        print("    sudo yum install automake cmake gcc gcc-c++ libtool")
elif platform.system() == "Darwin":
    print("OS X detected")
    PLATFORM_OSX = True
    
    print("Install these dependencies:")
    print(
        "    xcodebuild -license\n"
        "    xcode-select --install\n"
        "    brew install autoconf automake"
    )
elif platform.system() == "Windows":
    print("Windows detected")
    sys.exit(
        "! Native Windows not supported, please install MSYS2:\n"
        + "! https://msys2.github.io/\n"
        + "! If you already have MSYS2 installed, run with the correct Python:\n"
        + "! /bin/python ./get-deps"
    )
elif os.name == "posix":
    print("POSIX platform detected")
    
    if "MSYS" in platform.system():
        print("MSYS2 detected")
        sys.exit(
            "! MSYS2 not supported, please install MINGW64 or MINGW32:\n"
            + "! pacman -S mingw-w64-x86_64-toolchain   (for 64-bit builds)\n"
            + "!   OR\n"
            + "! pacman -S mingw-w64-i686-toolchain     (for 32-bit builds)"
        )
    elif "MINGW64" in platform.system():
        print("MSYS2 + MINGW64 detected")
        PLATFORM_WINDOWS    = True
        PLATFORM_WINDOWS_64 = True
        
        print("Install these dependencies: ")
        print("    pacman -S autoconf automake diffutils git make python tar tmux unzip")
        print("    pacman -S mingw-w64-x86_64-toolchain                        (for 64-bit builds)")
        print("    pacman -S mingw-w64-x86_64-cmake mingw-w64-x86_64-libtool   (for 64-bit builds)")
        print("    pacman -S mingw-w64-i686-toolchain                          (for 32-bit builds)")
        print("    pacman -S mingw-w64-i686-cmake mingw-w64-i686-libtool       (for 32-bit builds)")
    elif "MINGW32" in platform.system():
        print("MSYS2 + MINGW32 detected")
        PLATFORM_WINDOWS    = True
        PLATFORM_WINDOWS_32 = True
        
        print("Install these dependencies: ")
        print("    pacman -S autoconf automake diffutils git make python tar tmux unzip")
        print("    pacman -S mingw-w64-x86_64-toolchain                        (for 64-bit builds)")
        print("    pacman -S mingw-w64-x86_64-cmake mingw-w64-x86_64-libtool   (for 64-bit builds)")
        print("    pacman -S mingw-w64-i686-toolchain                          (for 32-bit builds)")
        print("    pacman -S mingw-w64-i686-cmake mingw-w64-i686-libtool       (for 32-bit builds)")
    else:
        print("Unsupported POSIX platform")
        sys.exit("! Unsupported platform!")
else:
    print("Unknown platform!")
    sys.exit("! Unsupported platform!")

print("")


# Available arguments
parser = argparse.ArgumentParser("update-tools")
parser.add_argument(
    "--no-build",
    action="store_true",
    help="Only download, do not install tools"
)

# Parse arguments
args = parser.parse_args()


# Amount of jobs to use when building
make_jobs = "-j" + str(multiprocessing.cpu_count())

# The directory containing this script
scriptDir = posixpath.dirname(posixpath.realpath(__file__))

# The directory to use as the temporary directory
tempDir = scriptDir + "/temp"

# Create temp directory if it doesn't exist
if not posixpath.exists(tempDir):
    os.makedirs(tempDir)

# The prefix directory
prefixDir = scriptDir + "/prefix"

# Create prefix directory if it doesn't exist
if not posixpath.exists(prefixDir):
    os.makedirs(prefixDir)


print("Script: " + scriptDir)
print("Temp:   " + tempDir)
print("Prefix: " + prefixDir)
print("")


#sys.exit()


def GitShallowClone(url, directory):
    """
    Do a shallow Git clone.
    
    :param url:        URL to clone from.
    :param directory:  Directory to clone into (relative to temp dir).
    """
    
    command = "git clone --depth=1 --branch=master " + url + " " + directory
    
    print("        ### Running download command: " + command)
    
    # Get GNU Readline
    output = subprocess.check_output(
        command,
        cwd = tempDir,
        stderr = subprocess.STDOUT,
        shell = True
    )
    
    return output


def GetParameter(paramName, param, linux, osx, windows, windows32, windows64):
    """
    Get a parameter based on OS.
    
    :returns: The original parameter or an OS specific one.
    """
    
    if PLATFORM_LINUX and linux:
        param = linux.get(paramName, param)
    elif PLATFORM_OSX and osx:
        param = osx.get(paramName, param)
    elif PLATFORM_WINDOWS_64 and windows64:
        if windows:
            param = windows.get(paramName, param)
        
        param = windows64.get(paramName, param)
    elif PLATFORM_WINDOWS_32 and windows32:
        if windows:
            param = windows.get(paramName, param)
        
        param = windows32.get(paramName, param)
    elif PLATFORM_WINDOWS and windows:
        param = windows.get(paramName, param)
    
    return param


def GetDependency(directory,
                  git = None,
                  download = None,
                  build = None,
                  linux = None,
                  osx = None,
                  windows = None,
                  windows32 = None,
                  windows64 = None):
    """
    Get dependency.
    """
    
    if posixpath.exists(tempDir + "/" + directory):
        print(
            "### Skipping " + directory + " because directory exists: "
            + tempDir + "/" + directory
        )
    else:
        print("### " + directory)
        
        git = GetParameter(
            "git",
            git,
            linux,
            osx,
            windows,
            windows32,
            windows64
        )
        download = GetParameter(
            "download",
            download,
            linux,
            osx,
            windows,
            windows32,
            windows64
        )
        build = GetParameter(
            "build",
            build,
            linux,
            osx,
            windows,
            windows32,
            windows64
        )
        
        if git:
            print("    ### Download " + directory)
            GitShallowClone(git, directory)
        
        if download:
            print("    ### Download " + directory)
            
            for command in download:
                print("        ### Running download command: " + command)
                
                subprocess.check_output(
                    command,
                    cwd = tempDir,
                    shell = True
                )
        
        if build and not args.no_build:
            print("    ### Build " + directory)
            
            for command in build:
                print("        ### Running build command: " + command)
                
                subprocess.check_output(
                    command,
                    cwd = tempDir + "/" + directory,
                    shell = True
                )
    
    print("")


# Get Premake (binaries only)
GetDependency(
    "premake5",
    linux = {
        "download": [
            "curl -sLo premake-5.0.0-alpha6.tar.gz "
            + "https://github.com/premake/premake-core/releases/download/"
            + "v5.0.0-alpha6/premake-5.0.0-alpha6-linux.tar.gz",
            "tar xf premake-5.0.0-alpha6.tar.gz"
        ]
    },
    osx = {
        "download": [
            "curl -sLo premake-5.0.0-alpha6.tar.gz "
            + "https://github.com/premake/premake-core/releases/download/"
            + "v5.0.0-alpha6/premake-5.0.0-alpha6-macosx.tar.gz",
            "tar xf premake-5.0.0-alpha6.tar.gz"
        ]
    },
    windows = {
        "download": [
            "curl -sLo premake-5.0.0-alpha6.zip "
            + "https://github.com/premake/premake-core/releases/download/"
            + "v5.0.0-alpha6/premake-5.0.0-alpha6-windows.zip",
            "unzip -o premake-5.0.0-alpha6.zip"
        ]
    }
)


# Get GLEW (source only)
GetDependency(
    "glew-1.13.0",
    download = [
        "curl -sLO https://sourceforge.net/projects/glew/files/glew/"
        + "1.13.0/glew-1.13.0.tgz",
        "tar xf glew-1.13.0.tgz"
    ]
)


# Get and compile Termcap (needed by GNU Readline, needed by Lua)
GetDependency(
    "termcap-1.3.1",
    linux = {
        "download": [
            "curl -sLO http://ftp.gnu.org/gnu/termcap/termcap-1.3.1.tar.gz",
            "tar xf termcap-1.3.1.tar.gz"
        ],
        "build": [
            "./configure --prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    }
)

# Get and compile GNU Readline (for Lua)
GetDependency(
    "readline-6.3",
    linux = {
        "download": [
            "curl -sLO ftp://ftp.cwru.edu/pub/bash/readline-6.3.tar.gz",
            "tar xf readline-6.3.tar.gz"
        ],
        "build": [
            "./configure --prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    }
)

# Get and compile Lua
GetDependency(
    "lua-5.3.1",
    download = [
        "curl -sLO http://www.lua.org/ftp/lua-5.3.1.tar.gz",
        "tar xf lua-5.3.1.tar.gz"
    ],
    linux = {
        "build": [
            "PATH=\"" + prefixDir + "/bin:$PATH\" "
            + "LIBRARY_PATH=\"$LIBRARY_PATH:" + prefixDir + "/lib/\" "
            + "LD_LIBRARY_PATH=\"$LD_LIBRARY_PATH:" + prefixDir + "/lib\" "
            + "C_INCLUDE_PATH=\"$C_INCLUDE_PATH:" + prefixDir + "/include\" "
            + "make " + make_jobs + " linux MYLIBS=-ltermcap",
            "make install INSTALL_TOP=\"" + prefixDir + "\""
        ]
    },
    osx = {
        "build": [
            "make " + make_jobs + " macosx",
            "make install INSTALL_TOP=\"" + prefixDir + "\""
        ]
    },
    windows = {
        "build": [
            "make " + make_jobs + " mingw",
            "make install INSTALL_TOP=\"" + prefixDir + "\"",
            "cp src/lua53.dll " + prefixDir + "/bin/"
        ]
    }
)


# Get and compile Luacheck
GetDependency(
    "luacheck",
    git = "https://github.com/mpeterv/luacheck.git",
    build = [
        "PATH=\"" + prefixDir + "/bin:$PATH\" ./install.lua " + prefixDir
    ]
)


# Get GLM
GetDependency(
    "glm-0.9.7.1",
    download = [
        "curl -sLO https://github.com/g-truc/glm/releases/download/"
        + "0.9.7.1/glm-0.9.7.1.zip",
        "unzip -o glm-0.9.7.1.zip",
        "mv glm glm-0.9.7.1"
    ]
    
)


# Get RapidXML
GetDependency(
    "rapidxml-1.13",
    download = [
        "curl -sLO http://downloads.sourceforge.net/project/rapidxml/"
        + "rapidxml/rapidxml%201.13/rapidxml-1.13.zip",
        "unzip -o rapidxml-1.13.zip"
    ]
)


# Get utf8cpp
GetDependency(
    "utf8cpp-2.3.4",
    download = [
        "curl -sLO http://downloads.sourceforge.net/project/utfcpp/"
        + "utf8cpp_2x/Release%202.3.4/utf8_v2_3_4.zip",
        "unzip -o utf8_v2_3_4.zip -d utf8cpp-2.3.4"
    ]
)


# Get and compile FreeType
GetDependency(
    "freetype-2.6.1",
    download = [
        "curl -sLO http://download.savannah.gnu.org/releases/freetype/"
        + "freetype-2.6.1.tar.gz",
        "tar xf freetype-2.6.1.tar.gz"
    ],
    linux = {
        "build": [
            "./configure --prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    osx = {
        "build": [
            "./configure --prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    windows64 = {
        "build": [
            "./configure "
            + "--build=x86_64-w64-mingw32 "
            + "--host=x86_64-w64-mingw32 "
            #+ "--target=x86_64-w64-mingw32 "
            + "--prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    windows32 = {
        "build": [
            "./configure "
            + "--build=i686-w64-mingw32 "
            + "--host=i686-w64-mingw32 "
            #+ "--target=i686-w64-mingw32 "
            + "--prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    }
)


# Get and compile libogg
GetDependency(
    "libogg-1.3.2",
    download = [
        "curl -sLO http://downloads.xiph.org/releases/ogg/libogg-1.3.2.tar.gz",
        "tar xf libogg-1.3.2.tar.gz"
    ],
    linux = {
        "build": [
            "./configure --prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    osx = {
        "build": [
            "./configure --prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    windows64 = {
        "build": [
            "./configure "
            + "--build=x86_64-w64-mingw32 "
            + "--host=x86_64-w64-mingw32 "
            #+ "--target=x86_64-w64-mingw32 "
            + "--prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    windows32 = {
        "build": [
            "./configure "
            + "--build=i686-w64-mingw32 "
            + "--host=i686-w64-mingw32 "
            #+ "--target=i686-w64-mingw32 "
            + "--prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    }
)

# Get and compile libvorbis
GetDependency(
    "libvorbis-1.3.5",
    download = [
        "curl -sLO http://downloads.xiph.org/releases/vorbis/"
        + "libvorbis-1.3.5.tar.gz",
        "tar xf libvorbis-1.3.5.tar.gz"
    ],
    linux = {
        "build": [
            "./configure --prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    osx = {
        "build": [
            "./configure --prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    windows64 = {
        "build": [
            "./configure "
            + "--build=x86_64-w64-mingw32 "
            + "--host=x86_64-w64-mingw32 "
            #+ "--target=x86_64-w64-mingw32 "
            + "--prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    windows32 = {
        "build": [
            "./configure "
            + "--build=i686-w64-mingw32 "
            + "--host=i686-w64-mingw32 "
            #+ "--target=i686-w64-mingw32 "
            + "--prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    }
)


# Get and compile OpenAL Soft
GetDependency(
    "openal-soft-1.16.0",
    download = [
        "curl -sLO http://kcat.strangesoft.net/openal-releases/"
        + "openal-soft-1.16.0.tar.bz2",
        "tar xf openal-soft-1.16.0.tar.bz2"
    ],
    linux = {
        "build": [
            "cd build; cmake -DCMAKE_INSTALL_PREFIX:PATH=" + prefixDir + " ..",
            "cd build; make " + make_jobs,
            "cd build; make install"
        ]
    },
    osx = {
        "build": [
            "cd build; cmake -DCMAKE_INSTALL_PREFIX:PATH=" + prefixDir + " ..",
            "cd build; make",
            "cd build; make install"
        ]
    },
    windows = {
        "build": [
            "cd build; cmake -G \"MSYS Makefiles\" "
            + "-DCMAKE_INSTALL_PREFIX:PATH=" + prefixDir + " ..",
            "cd build; make",
            "cd build; make install"
        ]
    }
)

# Get OpenAL Soft binaries (Windows)
GetDependency(
    "openal-soft-1.16.0-bin",
    windows = {
        "download": [
            "curl -sLO http://kcat.strangesoft.net/openal-soft-1.16.0-bin.zip",
            "unzip -o openal-soft-1.16.0-bin.zip"
        ]
    }
)


# Get and compile SDL2
GetDependency(
    "SDL2-2.0.3",
    download = [
        "curl -sLO https://www.libsdl.org/release/SDL2-2.0.3.tar.gz",
        "tar xf SDL2-2.0.3.tar.gz"
    ],
    linux = {
        "build": [
            "./autogen.sh",
            "./configure --prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    osx = {
        "build": [
            "CC=" + tempDir + "/SDL2-2.0.3/build-scripts/gcc-fat.sh "
            + "./configure --prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    windows64 = {
        "build": [
            "./autogen.sh",
            "./configure "
            + "--build=x86_64-w64-mingw32 "
            + "--host=x86_64-w64-mingw32 "
            #+ "--target=x86_64-w64-mingw32 "
            + "--prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    windows32 = {
        "build": [
            "./autogen.sh",
            "./configure "
            + "--build=i686-w64-mingw32 "
            + "--host=i686-w64-mingw32 "
            #+ "--target=i686-w64-mingw32 "
            + "--prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    }
)


# Get and compile zlib (needed by libpng, needed by SDL2_image)
GetDependency(
    "zlib-1.2.8",
    download = [
        "curl -sLO http://zlib.net/zlib-1.2.8.tar.gz",
        "tar xf zlib-1.2.8.tar.gz"
    ],
    linux = {
        "build": [
            "./configure --prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    osx = {
        "build": [
            "./configure --prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    windows = {
        "build": [
            "make "
            + "-f win32/Makefile.gcc "
            + "BINARY_PATH=" + prefixDir + "/bin "
            + "INCLUDE_PATH=" + prefixDir + "/include "
            + "LIBRARY_PATH=" + prefixDir + "/lib "
            + "install",
            "cp zlib1.dll " + prefixDir + "/bin"
        ]
    }
)

# Get and compile libpng (needed by SDL2_image)
GetDependency(
    "libpng-1.6.18",
    download = [
        "curl -sLO ftp://ftp.simplesystems.org/pub/libpng/png/src/"
        + "libpng16/libpng-1.6.18.tar.gz",
        "tar xf libpng-1.6.18.tar.gz"
    ],
    linux = {
        "build": [
            "CPPFLAGS=\"-I" + prefixDir + "/include\" "
            + "LDFLAGS=\"-L" + prefixDir + "/lib\" "
            + "./configure --prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    osx = {
        "build": [
            "CPPFLAGS=\"-I" + prefixDir + "/include\" "
            + "LDFLAGS=\"-L" + prefixDir + "/lib\" "
            + "./configure --prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    windows64 = {
        "build": [
            "./configure "
            + "--build=x86_64-w64-mingw32 "
            + "--host=x86_64-w64-mingw32 "
            #+ "--target=x86_64-w64-mingw32 "
            + "--prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    windows32 = {
        "build": [
            "./configure "
            + "--build=i686-w64-mingw32 "
            + "--host=i686-w64-mingw32 "
            #+ "--target=i686-w64-mingw32 "
            + "--prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    }
)

# Get and compile libjpeg (needed by SDL2_image)
GetDependency(
    "jpeg-9a",
    download = [
        "curl -sLO http://www.ijg.org/files/jpegsrc.v9a.tar.gz",
        "tar xf jpegsrc.v9a.tar.gz"
    ],
    linux = {
        "build": [
            "./configure --prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    osx = {
        "build": [
            "./configure --prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    windows64 = {
        "build": [
            "./configure "
            + "--build=x86_64-w64-mingw32 "
            + "--host=x86_64-w64-mingw32 "
            #+ "--target=x86_64-w64-mingw32 "
            + "--prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    windows32 = {
        "build": [
            "./configure "
            + "--build=i686-w64-mingw32 "
            + "--host=i686-w64-mingw32 "
            #+ "--target=i686-w64-mingw32 "
            + "--prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    }
)

# Get and compile libtiff (needed by SDL2_image)
GetDependency(
    "tiff-4.0.6",
    download = [
        "curl -sLO ftp://ftp.remotesensing.org/pub/libtiff/tiff-4.0.6.tar.gz",
        "tar xf tiff-4.0.6.tar.gz"
    ],
    linux = {
        "build": [
            "./configure --prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    osx = {
        "build": [
            "./configure --prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    windows64 = {
        "build": [
            "./configure "
            + "--build=x86_64-w64-mingw32 "
            + "--host=x86_64-w64-mingw32 "
            #+ "--target=x86_64-w64-mingw32 "
            + "--prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    windows32 = {
        "build": [
            "./configure "
            + "--build=i686-w64-mingw32 "
            + "--host=i686-w64-mingw32 "
            #+ "--target=i686-w64-mingw32 "
            + "--prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    }
)

# Get and compile SDL2_image
GetDependency(
    "SDL2_image-2.0.0",
    download = [
        "curl -sLO https://www.libsdl.org/projects/SDL_image/release/"
        + "SDL2_image-2.0.0.tar.gz",
        "tar xf SDL2_image-2.0.0.tar.gz"
    ],
    linux = {
        "build": [
            "./autogen.sh",
            "PATH=\"" + prefixDir + "/bin:$PATH\" "
            + "CFLAGS=\"-I" + prefixDir + "/include\" "
            + "C_INCLUDE_PATH=\"" + prefixDir + "/include\" "
            + "./configure --prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    osx = {
        "build": [
            "./autogen.sh",
            "PATH=\"" + prefixDir + "/bin:$PATH\" "
            + "CFLAGS=\"-I" + prefixDir + "/include\" "
            + "C_INCLUDE_PATH=\"" + prefixDir + "/include\" "
            + "./configure --prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    windows64 = {
        "build": [
            "./autogen.sh",
            "PATH=\"" + prefixDir + "/bin:$PATH\" "
            + "CFLAGS=\"-I" + prefixDir + "/include\" "
            + "C_INCLUDE_PATH=\"" + prefixDir + "/include\" "
            + "./configure "
            + "--build=x86_64-w64-mingw32 "
            + "--host=x86_64-w64-mingw32 "
            #+ "--target=x86_64-w64-mingw32 "
            + "--prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    windows32 = {
        "build": [
            "./autogen.sh",
            "PATH=\"" + prefixDir + "/bin:$PATH\" "
            + "CFLAGS=\"-I" + prefixDir + "/include\" "
            + "C_INCLUDE_PATH=\"" + prefixDir + "/include\" "
            + "./configure "
            + "--build=i686-w64-mingw32 "
            + "--host=i686-w64-mingw32 "
            #+ "--target=i686-w64-mingw32 "
            + "--prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    }
)


# Get and compile PCRE (needed by SWIG)
GetDependency(
    "pcre-8.37",
    download = [
        "curl -sLO ftp://ftp.csx.cam.ac.uk/pub/software/programming/"
        + "pcre/pcre-8.37.tar.gz",
        "tar xf pcre-8.37.tar.gz"
    ],
    linux = {
        "build": [
            "./configure --disable-shared --prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    osx = {
        "build": [
            "./configure --disable-shared --prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    windows64 = {
        "build": [
            "./configure --disable-shared "
            + "--build=x86_64-w64-mingw32 "
            + "--host=x86_64-w64-mingw32 "
            #+ "--target=x86_64-w64-mingw32 "
            + "--prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    windows32 = {
        "build": [
            "./configure --disable-shared "
            + "--build=i686-w64-mingw32 "
            + "--host=i686-w64-mingw32 "
            #+ "--target=i686-w64-mingw32 "
            + "--prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    }
)

# Get and compile SWIG
GetDependency(
    "swig-3.0.7",
    download = [
        "curl -sLO http://prdownloads.sourceforge.net/swig/swig-3.0.7.tar.gz",
        "tar xf swig-3.0.7.tar.gz"
    ],
    linux = {
        "build": [
            "./autogen.sh",
            "PATH=\"" + prefixDir + "/bin:$PATH\" "
            + "./configure "
            + "--with-pcre-prefix=" + prefixDir + " "
            + "--prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    osx = {
        "build": [
            "./autogen.sh",
            "PATH=\"" + prefixDir + "/bin:$PATH\" "
            + "./configure "
            + "--with-pcre-prefix=" + prefixDir + " "
            + "--prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    windows64 = {
        "build": [
            "./autogen.sh",
            "./configure "
            + "--build=x86_64-w64-mingw32 "
            + "--host=x86_64-w64-mingw32 "
            #+ "--target=x86_64-w64-mingw32 "
            + "--with-pcre-prefix=" + prefixDir + " "
            + "--prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    windows32 = {
        "build": [
            "./autogen.sh",
            "./configure "
            + "--build=i686-w64-mingw32 "
            + "--host=i686-w64-mingw32 "
            #+ "--target=i686-w64-mingw32 "
            + "--with-pcre-prefix=" + prefixDir + " "
            + "--prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    }
)


# Get and compile Uncrustify
GetDependency(
    "uncrustify-0.61",
    download = [
        "curl -sLO http://sourceforge.net/projects/uncrustify/files/uncrustify/"
        + "uncrustify-0.61/uncrustify-0.61.tar.gz",
        "tar xf uncrustify-0.61.tar.gz"
    ],
    build = [
        "./configure --prefix=" + prefixDir,
        "make " + make_jobs,
        "make install"
    ],
    windows64 = {
        "build": [
            "./configure "
            + "--build=x86_64-w64-mingw32 "
            + "--host=x86_64-w64-mingw32 "
            #+ "--target=x86_64-w64-mingw32 "
            + "--prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    },
    windows32 = {
        "build": [
            "./configure "
            + "--build=i686-w64-mingw32 "
            + "--host=i686-w64-mingw32 "
            #+ "--target=i686-w64-mingw32 "
            + "--prefix=" + prefixDir,
            "make " + make_jobs,
            "make install"
        ]
    }
)


# Get Gcovr
GetDependency(
    "gcovr-3.2",
    download = [
        "curl -sLo gcovr-3.2.tar.gz "
        + "https://github.com/gcovr/gcovr/archive/3.2.tar.gz",
        "tar xf gcovr-3.2.tar.gz"
    ],
    build = [
        #"python setup.py build",
        "mkdir -p " + prefixDir + "/bin/",
        #"cp build/scripts-2.7/gcovr " + prefixDir + "/bin/"
        "cp scripts/gcovr " + prefixDir + "/bin/"
        #,
        #"PYTHONPATH=" + prefixDir + "/lib/python2.7/site-packages "
        #+ "python setup.py install --prefix=" + prefixDir
    ]
)


# Get Qt
GetDependency(
    "Qt",
    linux = {
        "download": [
            "curl -sLO http://download.qt.io/official_releases/"
            + "online_installers/qt-unified-linux-x64-online.run",
            "chmod a+x qt-unified-linux-x64-online.run",
            "mkdir Qt",
            "mv qt-unified-linux-x64-online.run Qt"
        ],
        "build": [
            "./qt-unified-linux-x64-online.run; exit 0"
        ]
    },
    osx = {
        "download": [
            "curl -sLO http://download.qt.io/official_releases/"
            + "online_installers/qt-unified-mac-x64-online.dmg",
            "mkdir Qt",
            "mv qt-unified-mac-x64-online.dmg Qt"
        ]
        #"build": [
        #    "./qt-unified-mac-x64-online.dmg; exit 0"
        #]
    },
    windows = {
        "download": [
            "curl -sLO http://download.qt.io/official_releases/"
            + "online_installers/qt-unified-windows-x86-online.exe",
            "mkdir Qt",
            "mv qt-unified-windows-x86-online.exe Qt"
        ],
        "build": [
            "./qt-unified-windows-x86-online.exe; exit 0"
        ]
    }
)
