#if defined SWIG

// Module name
%module GL

%begin %{
// Ignore all warnings from source code generated by SWIG
#pragma GCC diagnostic ignored "-W"
#pragma GCC diagnostic ignored "-Wall"
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wsign-compare"
#pragma GCC diagnostic ignored "-Wunused-variable"
%}

%{
#include <QOpenGLFunctions>
%}

// OpenGL typedefs, defines and functions
//%include "swig_opengl.h"
%include "swig_gl3.h"

#endif // defined SWIG
