#!/usr/bin/env python

"""
Build the job.
"""

import subprocess


print("")
print("[CONFIGURE]")
print("")

try:
    # Run Premake
    subprocess.check_output(
        ["./configure"]
    )
except subprocess.CalledProcessError as e:
    print e.message
    raise

print("")
print("[BUILDING HACTENGINE (RELEASE)]")
print("")

try:
    # Build
    subprocess.check_output(
        ["./compile", "config=release"]
    )
except subprocess.CalledProcessError as e:
    print e.message
    raise

print("")
print("[BUILDING HACTENGINE (DEBUG)]")
print("")

try:
    # Build
    subprocess.check_output(
        ["./compile", "config=debug"]
    )
except subprocess.CalledProcessError as e:
    print e.message
    raise

print("")
print("[DONE BUILDING]")
print("")
