#!/usr/bin/env python

"""
Build the job.
"""

import subprocess


print("")
print("[CONFIGURE]")
print("")

# Run Premake
subprocess.check_call(
    ["./configure"]
)

print("")
print("[BUILDING HACTENGINE (DEBUG)]")
print("")

# Build
subprocess.check_call(
    ["./compile"]
)

print("")
print("[BUILDING HACTENGINE (RELEASE)]")
print("")

# Build
subprocess.check_call(
    ["./compile", "config=release"]
)

print("")
print("[DONE BUILDING]")
print("")
