#!/usr/bin/env python

"""
Run HactEngine.
"""

import atexit
import os
import platform
import subprocess


print("")
print("[RUNNING HACTENGINE (DEBUG)]")
print("")

if not os.path.exists("engine"):
    # Create fake engine folder
    os.symlink(".", "engine")

# Remove the temporary symlink at exit
atexit.register(
    lambda:
        os.remove("engine")
)


timeoutCommand = "timeout"

if platform.system() == "Darwin":
    timeoutCommand = "gtimeout"

# Run HactEngine (debug build)
subprocess.call(
    [
        timeoutCommand,
        "--preserve-status",
        "15s",
        "./build/Debug/HactEngine"
    ]
)


print("")
print("[RUNNING HACTENGINE (RELEASE)]")
print("")

# Run HactEngine (release build)
subprocess.call(
    [
       timeoutCommand,
        "--preserve-status",
        "15s",
        "./build/Release/HactEngine"
    ]
)

print("")
print("[DONE RUNNING HACTENGINE]")
print("")
