#!/usr/bin/env python

"""
Run HactEngine.
"""

import os
import platform
import subprocess


print("")
print("[RUNNING HACTENGINE (DEBUG)]")
print("")

if not os.path.exists("engine"):
    # Create fake engine folder
    os.symlink(".", "engine")

timeoutCommand = "timeout"

if platform.system() == "Darwin":
    timeoutCommand = "gtimeout"

# Run HactEngine (debug build)
subprocess.call(
    [
        timeoutCommand,
        "--preserve-status",
        "15s",
        "../run",
        "config=debug"
    ],
    cwd = "build"
)


print("")
print("[RUNNING HACTENGINE (RELEASE)]")
print("")

# Run HactEngine (release build)
subprocess.call(
    [
       timeoutCommand,
        "--preserve-status",
        "15s",
        "../run",
        "config=release"
    ],
    cwd = "build"
)

print("")
print("[DONE RUNNING HACTENGINE]")
print("")
