#!/usr/bin/env python

"""
Run tests.
"""

import subprocess


print("")
print("[RUNNING TESTS]")
print("")

try:
    # Run tests
    subprocess.check_output(
        ["./configure", "--run-tests"],
        cwd = "tests"
    )
    subprocess.check_output(
        ["./compile", "--run-tests"],
        cwd = "tests"
    )
except subprocess.CalledProcessError as e:
    print e.message
    raise

print("")
print("[DONE RUNNING TESTS]")
print("")
