#!/usr/bin/env python

"""
Run tests.
"""

import subprocess


print("")
print("[RUNNING TESTS]")
print("")

# Run tests
subprocess.check_call(
    ["./configure", "--run-tests"],
    cwd = "."
)
subprocess.check_call(
    ["./compile", "--run-tests"],
    cwd = "."
)

print("")
print("[DONE RUNNING TESTS]")
print("")
