#!/usr/bin/env python

"""
Run tests.
"""

import subprocess


print("")
print("[RUNNING TESTS]")
print("")

# Run tests
subprocess.check_call(
    ["./configure --run-tests"],
    cwd = "tests"
)
subprocess.check_call(
    ["./compile --run-tests"],
    cwd = "tests"
)

print("")
print("[DONE RUNNING TESTS]")
print("")
