#!/usr/bin/env python

#
# Build the job
#

import os
import subprocess
import sys


print("")
print("[BUILDING]")
print("")

# Run Premake
subprocess.check_call(
    ["./configure"]
)

# Build
subprocess.check_call(
    ["make", "-j8"]
)

print("")
print("[DONE BUILDING]")
print("")

