#!/usr/bin/env python

#
# Build the job
#

import os
import subprocess
import sys


print("")
print("[RUNNING TESTS]")
print("")

# Run tests
subprocess.check_call(
    ["./run-tests.sh"],
    cwd = "tests"
)

print("")
print("[DONE RUNNING TESTS]")
print("")

