#!/usr/bin/env python

#
# Build the job
#

import subprocess


print("")
print("[CONFIGURE]")
print("")

# Run Premake
subprocess.check_call(
    ["./configure"]
)

print("")
print("[BUILDING]")
print("")

# Build
subprocess.check_call(
    ["make", "-j8"]
)

print("")
print("[DONE BUILDING]")
print("")

