#!/usr/bin/env python

#
# Build the job
#

import os
import subprocess
import sys


# Add Qt to path
os.environ["PATH"] = "/usr/local/Qt-5.4.1/bin:$PATH"

print("")
print("[RUNNING TESTS]")
print("")

# Run tests
subprocess.check_call(
    ["./run-tests.sh"],
    cwd = "tests"
)

print("")
print("[DONE RUNNING TESTS]")
print("")

