#!/usr/bin/env python

"""
Initialize and display information about the job and environment.
"""

import os
import subprocess
import sys


print("[INIT]")

# Get current Git branch name
branch = None
try:
    branch = subprocess.check_output(
        ["git", "rev-parse", "--abbrev-ref", "HEAD"],
        stderr = open(os.devnull, 'w')
    )
    branch = branch.decode().rstrip()
except subprocess.CalledProcessError:
    pass

if branch == "HEAD":
    sys.exit("DETACHED HEAD!")

# Get currect Git commit tag
tag = None
try:
    tag = subprocess.check_output(
        ["git", "describe", "--exact-match"],
        stderr = open(os.devnull, 'w')
    )
    tag = tag.decode().rstrip()
except subprocess.CalledProcessError:
    pass


print("Branch: " + str(branch))
print("Tag:    " + str(tag))


# Checkout the corrent branch in submodules
subprocess.check_call(
    "git submodule foreach --recursive "
    + "'git checkout " + branch + " || git checkout master'",
    stderr = open(os.devnull, 'w'),
    shell = True
)

print("")
print("")

print("[COMMIT MESSAGE]")
print(
    subprocess.check_output(
        ["git", "log", "--format=%B", "-n", "1", "HEAD"]
    )
)
print("")

print("[VERSION INFO]")
print("")
subprocess.check_call(
    ["g++", "--version"]
)
subprocess.check_call(
    ["lua", "-v"]
)
subprocess.check_call(
    ["swig", "-version"]
)
print("")
subprocess.call(
    ["qmake", "--version"]
)
print("")
print("")
print("")
