#!/usr/bin/env python

"""
Build the job.
"""

import subprocess


print("")
print("[CONFIGURE]")
print("")

# Run Premake
subprocess.call(
    ["./configure"]
)

print("")
print("[BUILDING]")
print("")

# Build
subprocess.call(
    ["make", "-j8"],
    cwd = "build"
)


# FIXME: Somehow a second run of configure fixes things (maybe?)

# Run Premake
subprocess.check_call(
    ["./configure"]
)

# Build
subprocess.check_call(
    ["make", "-j8"],
    cwd = "build"
)

print("")
print("[DONE BUILDING]")
print("")
